// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rps;

namespace rps.Migrations
{
    [DbContext(typeof(GameContext))]
    partial class GameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("rps.DataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("GameMode")
                        .HasColumnType("int");

                    b.Property<string>("PlayerOneName")
                        .HasColumnType("text");

                    b.Property<string>("PlayerOneSelection")
                        .HasColumnType("text");

                    b.Property<string>("PlayerTwoName")
                        .HasColumnType("text");

                    b.Property<string>("PlayerTwoSelection")
                        .HasColumnType("text");

                    b.Property<string>("Winner")
                        .HasColumnType("text");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("GameData");
                });
#pragma warning restore 612, 618
        }
    }
}
